
//TODO Add Rest of Buildings
// TODO Add Redtails for C-Store
//  TODO add Foster
// and add Kenney for Bioethics
import 'package:flutter/material.dart';

final kBuildings = [
  'Abbott Stadium',
  'Brimmer',
  'Armstrong Hall',
  'Banneker Hall',
  'Basil O Connor Hall',
  'Bethune Hall',
  'Bioethics',
  'Booker T. Washington Monument',
  'Brimmer',
  'Campbell Hall',
  'Carnegie Hall',
  'Carver Foundation',
  'Centralized Laboratory Animal Research Facility',
  'Chambliss Business House',
  'Chappie James Arena',
  'Convenience Store',
  'Douglass Hall',
  'East Commons',
  'Emery I',
  'Emery II',
  'Emery III',
  'Emery IV',
  'Emery Recreation Building',
  'Engineering Building',
  'Ford Library',
  'George Washington Carver Museum',
  'Harper Hall',
  'Harvey Hall',
  'Henderson Hall',
  'Housing',
  'Huntington Hall',
  'James Hall',
  'Kellogg Hotel and Conference Center',
  'Kresge Center',
  'Large Animal Clinic',
  'Lewis Adams Hall',
  'Logan Hall',
  'Marable Courts',
  'Margaret Murray Washington Hall',
  'Milbank Hall',
  'Morrison Mayberry Hall',
  'North Commons',
  'Old Adminsitration Building',
  'Olivia Davidson Hall',
  'Patterson Hall',
  'Physical Plant',
  'Post Mortem Building',
  'Power Plant',
  'Robert Circle',
  'Robert R. Moton Hall',
  'Rockefeller Hall',
  'Rosenwald Hall',
  'ROTC',
  'Russell Hall',
  'Russell Nursery',
  'Sage Hall',
  'Small Animal Clinic',
  'Softball Field',
  'Tantum Hall',
  'Tennis Court',
  'The Oaks',
  'Thrasher Hall',
  'Tompkins Hall',
  'Tuskegee Univ. Police Dept.',
  'University Apartment',
  'University Chapel',
  'Washington Field',
  'West Commons',
  'White Hall',
  'WIlcox A',
  'Wilcox B',
  'Wilcox C',
  'Wilcox D',
  'Wilcox E',
  'William V. Chambliss House',
  'Williams - Bowie Hall',
  'Younge Hall',

];
final String kBrimmerInfo = 'The College of Business and Information Science, located in the new Andrew F. Brimmer Hall, is a direct outgrowth of Tuskegee University’s historical mission and its emphasis on economic empowerment and business development. From its inception, Tuskegee has been a highly recognized and visible institution committed to the values of self help, business development and lifelong learning';
final kRecentBuildings = [
  'Brimmer',
  "Carnegie",
];
final kMainYellow = Color(0xffE3B821);
